package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;

/**
 *CDd generated by hbm2java
 */

@Entity
@Table(name = "CD")
@PrimaryKeyJoinColumn(name = "ID_Material")
public class CD extends Material implements java.io.Serializable {


     @Column(name = "Genero")
     private String genero;
     @Column(name = "Duracion")
     @Temporal(TemporalType.TIME)
     private Date duracion;
     @Column(name = "Numero_Canciones")
     private Integer numeroCanciones;

    public CD() {
    }

    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Date getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }
    public Integer getNumeroCanciones() {
        return this.numeroCanciones;
    }
    
    public void setNumeroCanciones(Integer numeroCanciones) {
        this.numeroCanciones = numeroCanciones;
    }




}


