package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cd generated by hbm2java
 */
public class Cd  implements java.io.Serializable {


     private int idMaterial;
     private Material material;
     private String genero;
     private Date duracion;
     private Integer numeroCanciones;

    public Cd() {
    }

	
    public Cd(Material material) {
        this.material = material;
    }
    public Cd(Material material, String genero, Date duracion, Integer numeroCanciones) {
       this.material = material;
       this.genero = genero;
       this.duracion = duracion;
       this.numeroCanciones = numeroCanciones;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Date getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }
    public Integer getNumeroCanciones() {
        return this.numeroCanciones;
    }
    
    public void setNumeroCanciones(Integer numeroCanciones) {
        this.numeroCanciones = numeroCanciones;
    }




}


