package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ejemplar generated by hbm2java
 */
public class Ejemplar  implements java.io.Serializable {


     private Integer idEjemplar;
     private Material material;
     private String codigoBarra;
     private String estado;
     private String ubicacionFisica;
     private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

    public Ejemplar() {
    }

    public Ejemplar(Material material, String codigoBarra, String estado, String ubicacionFisica, Set<Prestamo> prestamos) {
       this.material = material;
       this.codigoBarra = codigoBarra;
       this.estado = estado;
       this.ubicacionFisica = ubicacionFisica;
       this.prestamos = prestamos;
    }
   
    public Integer getIdEjemplar() {
        return this.idEjemplar;
    }
    
    public void setIdEjemplar(Integer idEjemplar) {
        this.idEjemplar = idEjemplar;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public String getCodigoBarra() {
        return this.codigoBarra;
    }
    
    public void setCodigoBarra(String codigoBarra) {
        this.codigoBarra = codigoBarra;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getUbicacionFisica() {
        return this.ubicacionFisica;
    }
    
    public void setUbicacionFisica(String ubicacionFisica) {
        this.ubicacionFisica = ubicacionFisica;
    }
    public Set<Prestamo> getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set<Prestamo> prestamos) {
        this.prestamos = prestamos;
    }




}


