package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1



/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private int idMaterial;
     private Material material;
     private String isbn;
     private Integer numeroPaginas;

    public Libro() {
    }

	
    public Libro(Material material) {
        this.material = material;
    }
    public Libro(Material material, String isbn, Integer numeroPaginas) {
       this.material = material;
       this.isbn = isbn;
       this.numeroPaginas = numeroPaginas;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public Integer getNumeroPaginas() {
        return this.numeroPaginas;
    }
    
    public void setNumeroPaginas(Integer numeroPaginas) {
        this.numeroPaginas = numeroPaginas;
    }




}


