package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

/**
 * Material generated by hbm2java
 */

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = "Material")
public  abstract class Material  implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_Material")
     private Integer idMaterial;
     private String titulo;
     private String autor;
     private String editorial;
     private Date anio;
     @Enumerated(EnumType.STRING)
     @Column(name = "Tipo_Material")
     private TipoMaterial tipoMaterial;
     private String ubicacionFisica;
     private Integer cantidadEjemplares;
     private CD cd;
     private Tesis tesis;
     private Libro libro;
     private Revista revista;
     private Set<Ejemplar> ejemplars = new HashSet<Ejemplar>(0);

     public enum TipoMaterial {
            Libro, Revista, CD, Tesis
        }
     
    public Material() {
    }

	
    public Material(String titulo, TipoMaterial tipoMaterial) {
        this.titulo = titulo;
        this.tipoMaterial = tipoMaterial;
    }
    public Material(String titulo, String autor, String editorial, Date anio, TipoMaterial tipoMaterial, String ubicacionFisica, Integer cantidadEjemplares, CD cd, Tesis tesis, Libro libro, Revista revista, Set<Ejemplar> ejemplars) {
       this.titulo = titulo;
       this.autor = autor;
       this.editorial = editorial;
       this.anio = anio;
       this.tipoMaterial = tipoMaterial;
       this.ubicacionFisica = ubicacionFisica;
       this.cantidadEjemplares = cantidadEjemplares;
       this.cd = cd;
       this.tesis = tesis;
       this.libro = libro;
       this.revista = revista;
       this.ejemplars = ejemplars;
    }
   
    public Integer getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(Integer idMaterial) {
        this.idMaterial = idMaterial;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public Date getAnio() {
        return this.anio;
    }
    
    public void setAnio(Date anio) {
        this.anio = anio;
    }
    public TipoMaterial getTipoMaterial() {
    return tipoMaterial;
    }

    public void setTipoMaterial(TipoMaterial tipoMaterial) {
    this.tipoMaterial = tipoMaterial;
    }
    public String getUbicacionFisica() {
        return this.ubicacionFisica;
    }
    
    public void setUbicacionFisica(String ubicacionFisica) {
        this.ubicacionFisica = ubicacionFisica;
    }
    public Integer getCantidadEjemplares() {
        return this.cantidadEjemplares;
    }
    
    public void setCantidadEjemplares(Integer cantidadEjemplares) {
        this.cantidadEjemplares = cantidadEjemplares;
    }
    public CD getCd() {
        return this.cd;
    }
    
    public void setCd(CD cd) {
        this.cd = cd;
    }
    public Tesis getTesis() {
        return this.tesis;
    }
    
    public void setTesis(Tesis tesis) {
        this.tesis = tesis;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public Revista getRevista() {
        return this.revista;
    }
    
    public void setRevista(Revista revista) {
        this.revista = revista;
    }
    public Set<Ejemplar> getEjemplars() {
        return this.ejemplars;
    }
    
    public void setEjemplars(Set<Ejemplar> ejemplars) {
        this.ejemplars = ejemplars;
    }




}


