package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private Integer idMaterial;
     private String titulo;
     private String autor;
     private String editorial;
     private Date anio;
     private String tipoMaterial;
     private String ubicacionFisica;
     private Integer cantidadEjemplares;
     private Cd cd;
     private Tesis tesis;
     private Libro libro;
     private Revista revista;
     private Set<Ejemplar> ejemplars = new HashSet<Ejemplar>(0);

    public Material() {
    }

	
    public Material(String titulo, String tipoMaterial) {
        this.titulo = titulo;
        this.tipoMaterial = tipoMaterial;
    }
    public Material(String titulo, String autor, String editorial, Date anio, String tipoMaterial, String ubicacionFisica, Integer cantidadEjemplares, Cd cd, Tesis tesis, Libro libro, Revista revista, Set<Ejemplar> ejemplars) {
       this.titulo = titulo;
       this.autor = autor;
       this.editorial = editorial;
       this.anio = anio;
       this.tipoMaterial = tipoMaterial;
       this.ubicacionFisica = ubicacionFisica;
       this.cantidadEjemplares = cantidadEjemplares;
       this.cd = cd;
       this.tesis = tesis;
       this.libro = libro;
       this.revista = revista;
       this.ejemplars = ejemplars;
    }
   
    public Integer getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(Integer idMaterial) {
        this.idMaterial = idMaterial;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public Date getAnio() {
        return this.anio;
    }
    
    public void setAnio(Date anio) {
        this.anio = anio;
    }
    public String getTipoMaterial() {
        return this.tipoMaterial;
    }
    
    public void setTipoMaterial(String tipoMaterial) {
        this.tipoMaterial = tipoMaterial;
    }
    public String getUbicacionFisica() {
        return this.ubicacionFisica;
    }
    
    public void setUbicacionFisica(String ubicacionFisica) {
        this.ubicacionFisica = ubicacionFisica;
    }
    public Integer getCantidadEjemplares() {
        return this.cantidadEjemplares;
    }
    
    public void setCantidadEjemplares(Integer cantidadEjemplares) {
        this.cantidadEjemplares = cantidadEjemplares;
    }
    public Cd getCd() {
        return this.cd;
    }
    
    public void setCd(Cd cd) {
        this.cd = cd;
    }
    public Tesis getTesis() {
        return this.tesis;
    }
    
    public void setTesis(Tesis tesis) {
        this.tesis = tesis;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public Revista getRevista() {
        return this.revista;
    }
    
    public void setRevista(Revista revista) {
        this.revista = revista;
    }
    public Set<Ejemplar> getEjemplars() {
        return this.ejemplars;
    }
    
    public void setEjemplars(Set<Ejemplar> ejemplars) {
        this.ejemplars = ejemplars;
    }




}


