package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mora generated by hbm2java
 */
public class Mora  implements java.io.Serializable {


     private Integer idMora;
     private Prestamo prestamo;
     private BigDecimal monto;
     private Integer diasAtraso;

    public Mora() {
    }

    public Mora(Prestamo prestamo, BigDecimal monto, Integer diasAtraso) {
       this.prestamo = prestamo;
       this.monto = monto;
       this.diasAtraso = diasAtraso;
    }
   
    public Integer getIdMora() {
        return this.idMora;
    }
    
    public void setIdMora(Integer idMora) {
        this.idMora = idMora;
    }
    public Prestamo getPrestamo() {
        return this.prestamo;
    }
    
    public void setPrestamo(Prestamo prestamo) {
        this.prestamo = prestamo;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Integer getDiasAtraso() {
        return this.diasAtraso;
    }
    
    public void setDiasAtraso(Integer diasAtraso) {
        this.diasAtraso = diasAtraso;
    }




}


