package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer idPrestamo;
     private Ejemplar ejemplar;
     private Usuario usuario;
     private Date fechaPrestamo;
     private Date fechaDevolucionProgramada;
     private String devuelto;
     private Set<Mora> moras = new HashSet<Mora>(0);

    public Prestamo() {
    }

    public Prestamo(Ejemplar ejemplar, Usuario usuario, Date fechaPrestamo, Date fechaDevolucionProgramada, String devuelto, Set<Mora> moras) {
       this.ejemplar = ejemplar;
       this.usuario = usuario;
       this.fechaPrestamo = fechaPrestamo;
       this.fechaDevolucionProgramada = fechaDevolucionProgramada;
       this.devuelto = devuelto;
       this.moras = moras;
    }
   
    public Integer getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(Integer idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Ejemplar getEjemplar() {
        return this.ejemplar;
    }
    
    public void setEjemplar(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaPrestamo() {
        return this.fechaPrestamo;
    }
    
    public void setFechaPrestamo(Date fechaPrestamo) {
        this.fechaPrestamo = fechaPrestamo;
    }
    public Date getFechaDevolucionProgramada() {
        return this.fechaDevolucionProgramada;
    }
    
    public void setFechaDevolucionProgramada(Date fechaDevolucionProgramada) {
        this.fechaDevolucionProgramada = fechaDevolucionProgramada;
    }
    public String getDevuelto() {
        return this.devuelto;
    }
    
    public void setDevuelto(String devuelto) {
        this.devuelto = devuelto;
    }
    public Set<Mora> getMoras() {
        return this.moras;
    }
    
    public void setMoras(Set<Mora> moras) {
        this.moras = moras;
    }




}


