package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1

import javax.persistence.*;

/**
 * Revista generated by hbm2java
 */
@Entity
@Table(name = "Revista")
@PrimaryKeyJoinColumn(name = "ID_Material")
public class Revista extends Material  implements java.io.Serializable {


     @Column(name = "Numero_Edicion")
     private String numeroEdicion;
     @Column(name = "Periodicidad")
     private String periodicidad;

    public Revista() {
    }
    
    public String getNumeroEdicion() {
        return this.numeroEdicion;
    }
    
    public void setNumeroEdicion(String numeroEdicion) {
        this.numeroEdicion = numeroEdicion;
    }
    public String getPeriodicidad() {
        return this.periodicidad;
    }
    
    public void setPeriodicidad(String periodicidad) {
        this.periodicidad = periodicidad;
    }




}


