package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1



/**
 * Revista generated by hbm2java
 */
public class Revista  implements java.io.Serializable {


     private int idMaterial;
     private Material material;
     private String numeroEdicion;
     private String periodicidad;

    public Revista() {
    }

	
    public Revista(Material material) {
        this.material = material;
    }
    public Revista(Material material, String numeroEdicion, String periodicidad) {
       this.material = material;
       this.numeroEdicion = numeroEdicion;
       this.periodicidad = periodicidad;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public String getNumeroEdicion() {
        return this.numeroEdicion;
    }
    
    public void setNumeroEdicion(String numeroEdicion) {
        this.numeroEdicion = numeroEdicion;
    }
    public String getPeriodicidad() {
        return this.periodicidad;
    }
    
    public void setPeriodicidad(String periodicidad) {
        this.periodicidad = periodicidad;
    }




}


