package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1



/**
 * Tesis generated by hbm2java
 */
public class Tesis  implements java.io.Serializable {


     private int idMaterial;
     private Material material;
     private String universidad;
     private String carrera;

    public Tesis() {
    }

	
    public Tesis(Material material) {
        this.material = material;
    }
    public Tesis(Material material, String universidad, String carrera) {
       this.material = material;
       this.universidad = universidad;
       this.carrera = carrera;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public String getUniversidad() {
        return this.universidad;
    }
    
    public void setUniversidad(String universidad) {
        this.universidad = universidad;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }




}


