package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String email;
     private String contrasena;
     private String rol;
     private String estadoCuenta;
     private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

    public Usuario() {
    }

	
    public Usuario(String rol) {
        this.rol = rol;
    }
    public Usuario(String nombre, String email, String contrasena, String rol, String estadoCuenta, Set<Prestamo> prestamos) {
       this.nombre = nombre;
       this.email = email;
       this.contrasena = contrasena;
       this.rol = rol;
       this.estadoCuenta = estadoCuenta;
       this.prestamos = prestamos;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getEstadoCuenta() {
        return this.estadoCuenta;
    }
    
    public void setEstadoCuenta(String estadoCuenta) {
        this.estadoCuenta = estadoCuenta;
    }
    public Set<Prestamo> getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set<Prestamo> prestamos) {
        this.prestamos = prestamos;
    }




}


