package Modelo;
// Generated 26-may-2025 2:25:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "Usuario")
public class Usuario  implements java.io.Serializable {

    public enum Rol {
        Administrador, Profesor, Alumno
    }
    
    public enum EstadoCuenta {
        Activo, Suspendido
    }
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_Usuario")
     private Integer idUsuario;
    @Column(name = "Nombre", nullable = false, length = 100)
     private String nombre;
    @Column(name = "Email", unique = true, nullable = false, length = 100)
     private String email;
    @Column(name = "Contrasena", nullable = false, length = 100)
     private String contrasena;
    @Enumerated(EnumType.STRING)
    @Column(name = "Rol", nullable = false)
     private Rol rol;
    @Enumerated(EnumType.STRING)
    @Column(name = "Estado_Cuenta", nullable = false)
     private EstadoCuenta estadoCuenta = EstadoCuenta.Activo;

     private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

    public Usuario() {
    }

   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Rol getRol() {
        return rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    public EstadoCuenta getEstadoCuenta() {
        return estadoCuenta;
    }

    public void setEstadoCuenta(EstadoCuenta estadoCuenta) {
        this.estadoCuenta = estadoCuenta;
    }
    public Set<Prestamo> getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set<Prestamo> prestamos) {
        this.prestamos = prestamos;
    }




}


